version: "3"
networks:
        internal:
                ipam:
                        driver: default
services:
        cba_ui:
                image: 'cba_ui'
                hostname: 'cba_ui'
                environment: 
                        - "HOST_IP=10.71.36.236"
                networks:
                        - internal
                ports:
                        - '8000:8000'
